# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import etlpay_pb2 as etlpay__pb2

GRPC_GENERATED_VERSION = "1.68.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

# Version check removed by tools/generate_proto.py

# RuntimeError check removed


class EtlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
            "/etlpay.EtlService/Ingest",
            request_serializer=etlpay__pb2.IngestRequest.SerializeToString,
            response_deserializer=etlpay__pb2.IngestResponse.FromString,
            _registered_method=True,
        )


class EtlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ingest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EtlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Ingest": grpc.unary_unary_rpc_method_handler(
            servicer.Ingest,
            request_deserializer=etlpay__pb2.IngestRequest.FromString,
            response_serializer=etlpay__pb2.IngestResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "etlpay.EtlService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("etlpay.EtlService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class EtlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ingest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/etlpay.EtlService/Ingest",
            etlpay__pb2.IngestRequest.SerializeToString,
            etlpay__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
